//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniCloud.Security.Services {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SecurityQuestions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SecurityQuestions() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UniCloud.Security.Services.Assets.Resources.SecurityQuestions", typeof(SecurityQuestions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 您小时候最好的朋友叫什么名字? 的本地化字符串。
        /// </summary>
        public static string BestChildhoodFriendQuestion {
            get {
                return ResourceManager.GetString("BestChildhoodFriendQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您小时候的昵称是什么? 的本地化字符串。
        /// </summary>
        public static string ChildhoodNicknameQuestion {
            get {
                return ResourceManager.GetString("ChildhoodNicknameQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您的第一辆汽车是什么颜色的? 的本地化字符串。
        /// </summary>
        public static string FirstCarColorQuestion {
            get {
                return ResourceManager.GetString("FirstCarColorQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您的第一辆汽车是什么品牌和型号? 的本地化字符串。
        /// </summary>
        public static string FirstCarMakeAndModelQuestion {
            get {
                return ResourceManager.GetString("FirstCarMakeAndModelQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您的第一份工作是在哪个城市? 的本地化字符串。
        /// </summary>
        public static string FirstJobCityQuestion {
            get {
                return ResourceManager.GetString("FirstJobCityQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您去年的度假地是哪里? 的本地化字符串。
        /// </summary>
        public static string LastVacationLocationQuestion {
            get {
                return ResourceManager.GetString("LastVacationLocationQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您外祖母姓什么? 的本地化字符串。
        /// </summary>
        public static string MaternalGrandmothersMaidenNameQuestion {
            get {
                return ResourceManager.GetString("MaternalGrandmothersMaidenNameQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您母亲姓什么? 的本地化字符串。
        /// </summary>
        public static string MothersMaidenNameQuestion {
            get {
                return ResourceManager.GetString("MothersMaidenNameQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您的宠物叫什么名字? 的本地化字符串。
        /// </summary>
        public static string PetNameQuestion {
            get {
                return ResourceManager.GetString("PetNameQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您六年级时是在哪所学校? 的本地化字符串。
        /// </summary>
        public static string SixthGradeSchoolNameQuestion {
            get {
                return ResourceManager.GetString("SixthGradeSchoolNameQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您父亲出生在哪一年? 的本地化字符串。
        /// </summary>
        public static string YearFatherWasBornQuestion {
            get {
                return ResourceManager.GetString("YearFatherWasBornQuestion", resourceCulture);
            }
        }
    }
}
