//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18046
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniCloud.Infrastructure {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CAFMStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CAFMStrings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UniCloud.Infrastructure.Resources.CAFMStrings", typeof(CAFMStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 活动名称 的本地化字符串。
        /// </summary>
        public static string ActionName {
            get {
                return ResourceManager.GetString("ActionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 活动类型 的本地化字符串。
        /// </summary>
        public static string ActionType {
            get {
                return ResourceManager.GetString("ActionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 座级 的本地化字符串。
        /// </summary>
        public static string AircraftRegional {
            get {
                return ResourceManager.GetString("AircraftRegional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 机号 的本地化字符串。
        /// </summary>
        public static string AircraftRegNumber {
            get {
                return ResourceManager.GetString("AircraftRegNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 机型 的本地化字符串。
        /// </summary>
        public static string AircraftType {
            get {
                return ResourceManager.GetString("AircraftType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 航空公司 的本地化字符串。
        /// </summary>
        public static string Airline {
            get {
                return ResourceManager.GetString("Airline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文档 的本地化字符串。
        /// </summary>
        public static string AttachDoc {
            get {
                return ResourceManager.GetString("AttachDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件名 的本地化字符串。
        /// </summary>
        public static string AttachDocFileName {
            get {
                return ResourceManager.GetString("AttachDocFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 商载(吨) 的本地化字符串。
        /// </summary>
        public static string CarryingCapacity {
            get {
                return ResourceManager.GetString("CarryingCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 还有未保存的修改，继续将放弃修改，是否继续？ 的本地化字符串。
        /// </summary>
        public static string ConfirmNavigateAwayFromRequestDetail {
            get {
                return ResourceManager.GetString("ConfirmNavigateAwayFromRequestDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认保存 的本地化字符串。
        /// </summary>
        public static string ConfirmNavigateAwayFromRequestDetailTitle {
            get {
                return ResourceManager.GetString("ConfirmNavigateAwayFromRequestDetailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建日期 的本地化字符串。
        /// </summary>
        public static string CreateDate {
            get {
                return ResourceManager.GetString("CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 交付年度 的本地化字符串。
        /// </summary>
        public static string DeliverAnnual {
            get {
                return ResourceManager.GetString("DeliverAnnual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 交付月份 的本地化字符串。
        /// </summary>
        public static string DeliverMonth {
            get {
                return ResourceManager.GetString("DeliverMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文号 的本地化字符串。
        /// </summary>
        public static string DocNumber {
            get {
                return ResourceManager.GetString("DocNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结束日期 的本地化字符串。
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 审批日期 的本地化字符串。
        /// </summary>
        public static string ExamineDate {
            get {
                return ResourceManager.GetString("ExamineDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注销日期 的本地化字符串。
        /// </summary>
        public static string ExportDate {
            get {
                return ResourceManager.GetString("ExportDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出方式 的本地化字符串。
        /// </summary>
        public static string ExportType {
            get {
                return ResourceManager.GetString("ExportType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出厂日期 的本地化字符串。
        /// </summary>
        public static string FactoryDate {
            get {
                return ResourceManager.GetString("FactoryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 引进日期 的本地化字符串。
        /// </summary>
        public static string ImportDate {
            get {
                return ResourceManager.GetString("ImportDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 引进方式 的本地化字符串。
        /// </summary>
        public static string ImportType {
            get {
                return ResourceManager.GetString("ImportType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 净增商载(吨) 的本地化字符串。
        /// </summary>
        public static string IncreaseCarryingCapacity {
            get {
                return ResourceManager.GetString("IncreaseCarryingCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 净增座位 的本地化字符串。
        /// </summary>
        public static string IncreaseSeatingCapacity {
            get {
                return ResourceManager.GetString("IncreaseSeatingCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否批准 的本地化字符串。
        /// </summary>
        public static string IsApproved {
            get {
                return ResourceManager.GetString("IsApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否完成 的本地化字符串。
        /// </summary>
        public static string IsFinished {
            get {
                return ResourceManager.GetString("IsFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开/关闭 的本地化字符串。
        /// </summary>
        public static string IsOpen {
            get {
                return ResourceManager.GetString("IsOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否在册 的本地化字符串。
        /// </summary>
        public static string IsOperation {
            get {
                return ResourceManager.GetString("IsOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否有效 的本地化字符串。
        /// </summary>
        public static string IsValid {
            get {
                return ResourceManager.GetString("IsValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 评审标记 的本地化字符串。
        /// </summary>
        public static string ManageFlag {
            get {
                return ResourceManager.GetString("ManageFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 管理状态 的本地化字符串。
        /// </summary>
        public static string ManageStatus {
            get {
                return ResourceManager.GetString("ManageStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 说明 的本地化字符串。
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 处理状态 的本地化字符串。
        /// </summary>
        public static string OpStatus {
            get {
                return ResourceManager.GetString("OpStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所有权人 的本地化字符串。
        /// </summary>
        public static string Owner {
            get {
                return ResourceManager.GetString("Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 执行年度 的本地化字符串。
        /// </summary>
        public static string PerformAnnual {
            get {
                return ResourceManager.GetString("PerformAnnual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 执行月份 的本地化字符串。
        /// </summary>
        public static string PerformMonth {
            get {
                return ResourceManager.GetString("PerformMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存失败，请检查！ 的本地化字符串。
        /// </summary>
        public static string SaveFail {
            get {
                return ResourceManager.GetString("SaveFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存成功！ 的本地化字符串。
        /// </summary>
        public static string SaveSuccess {
            get {
                return ResourceManager.GetString("SaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 座位 的本地化字符串。
        /// </summary>
        public static string SeatingCapacity {
            get {
                return ResourceManager.GetString("SeatingCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提交失败，请检查！ 的本地化字符串。
        /// </summary>
        public static string SendFail {
            get {
                return ResourceManager.GetString("SendFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提交成功！ 的本地化字符串。
        /// </summary>
        public static string SendSuccess {
            get {
                return ResourceManager.GetString("SendSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始日期 的本地化字符串。
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标题 的本地化字符串。
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 版本 的本地化字符串。
        /// </summary>
        public static string VersionNumber {
            get {
                return ResourceManager.GetString("VersionNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 年度 的本地化字符串。
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
    }
}
