//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAAC.Infrastructure {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CAFMStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CAFMStrings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CAAC.Infrastructure.Resources.CAFMStrings", typeof(CAFMStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 已审 的本地化字符串。
        /// </summary>
        public static string AnnualPlanPassJudge {
            get {
                return ResourceManager.GetString("AnnualPlanPassJudge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退回 的本地化字符串。
        /// </summary>
        public static string AnnualPlanReturn {
            get {
                return ResourceManager.GetString("AnnualPlanReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 待审 的本地化字符串。
        /// </summary>
        public static string AnnualPlanReview {
            get {
                return ResourceManager.GetString("AnnualPlanReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 草稿 的本地化字符串。
        /// </summary>
        public static string AnnualPlanStatusDraft {
            get {
                return ResourceManager.GetString("AnnualPlanStatusDraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提交 的本地化字符串。
        /// </summary>
        public static string AnnualPlanSubmited {
            get {
                return ResourceManager.GetString("AnnualPlanSubmited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 待提交 的本地化字符串。
        /// </summary>
        public static string AnnualPlanToSubmit {
            get {
                return ResourceManager.GetString("AnnualPlanToSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BasicData.XML 的本地化字符串。
        /// </summary>
        public static string BasicDataConfigFileName {
            get {
                return ResourceManager.GetString("BasicDataConfigFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BasicData 的本地化字符串。
        /// </summary>
        public static string BasicDataConfigType {
            get {
                return ResourceManager.GetString("BasicDataConfigType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 还有未保存的修改，继续将放弃修改，是否继续？ 的本地化字符串。
        /// </summary>
        public static string ConfirmNavigateAwayFromRequestDetail {
            get {
                return ResourceManager.GetString("ConfirmNavigateAwayFromRequestDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认保存 的本地化字符串。
        /// </summary>
        public static string ConfirmNavigateAwayFromRequestDetailTitle {
            get {
                return ResourceManager.GetString("ConfirmNavigateAwayFromRequestDetailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EMail.XML 的本地化字符串。
        /// </summary>
        public static string EMailConfigFileName {
            get {
                return ResourceManager.GetString("EMailConfigFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EMail 的本地化字符串。
        /// </summary>
        public static string EMailConfigType {
            get {
                return ResourceManager.GetString("EMailConfigType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新申请 的本地化字符串。
        /// </summary>
        public static string NewAnnualPlanTittle {
            get {
                return ResourceManager.GetString("NewAnnualPlanTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新申请 的本地化字符串。
        /// </summary>
        public static string NewRequestTitle {
            get {
                return ResourceManager.GetString("NewRequestTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运营 的本地化字符串。
        /// </summary>
        public static string OperationBusiness {
            get {
                return ResourceManager.GetString("OperationBusiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 民航局已审 的本地化字符串。
        /// </summary>
        public static string RequestStatusApprovedCAAC {
            get {
                return ResourceManager.GetString("RequestStatusApprovedCAAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发改委已审 的本地化字符串。
        /// </summary>
        public static string RequestStatusApprovedNDRC {
            get {
                return ResourceManager.GetString("RequestStatusApprovedNDRC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已关闭 的本地化字符串。
        /// </summary>
        public static string RequestStatusClosed {
            get {
                return ResourceManager.GetString("RequestStatusClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 草稿 的本地化字符串。
        /// </summary>
        public static string RequestStatusDraft {
            get {
                return ResourceManager.GetString("RequestStatusDraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已提交 的本地化字符串。
        /// </summary>
        public static string RequestStatusSubmited {
            get {
                return ResourceManager.GetString("RequestStatusSubmited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 待提交 的本地化字符串。
        /// </summary>
        public static string RequestStatusToSubmit {
            get {
                return ResourceManager.GetString("RequestStatusToSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存失败，请检查！ 的本地化字符串。
        /// </summary>
        public static string SaveFail {
            get {
                return ResourceManager.GetString("SaveFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存成功！ 的本地化字符串。
        /// </summary>
        public static string SaveSuccess {
            get {
                return ResourceManager.GetString("SaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提交失败，请检查！ 的本地化字符串。
        /// </summary>
        public static string SendFail {
            get {
                return ResourceManager.GetString("SendFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提交成功！ 的本地化字符串。
        /// </summary>
        public static string SendSuccess {
            get {
                return ResourceManager.GetString("SendSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 变更 的本地化字符串。
        /// </summary>
        public static string VersionChange {
            get {
                return ResourceManager.GetString("VersionChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 评审 的本地化字符串。
        /// </summary>
        public static string VersionToReview {
            get {
                return ResourceManager.GetString("VersionToReview", resourceCulture);
            }
        }
    }
}
